version: "3.9"

services:
  indexer-db:
    image: postgres:16.2-alpine
    container_name: indexer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: indexer-db
    ports:
      - 15432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-migrator:
    image: migrate/migrate
    depends_on:
      indexer-db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:1234@indexer-db:5432/indexer-db?sslmode=disable", "up"]
    restart: "no"  # Ensures that it does not keep restarting on failure

  indexer:
    build: .
    container_name: indexer
    environment:
      - DATABASE_URL=postgres://postgres:1234@indexer-db:5432/indexer-db
    depends_on:
      db-migrator:
        condition: service_completed_successfully
