// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cache struct {
	ID   string
	Data string
}

type RocketpoolTvl struct {
	ID          int32
	EthLocked   string
	RplLocked   string
	BlockNumber pgtype.Int8
}
